const CartActionTypes = {

    TOGGLE_CART_HIDDEN:'TOGGLE_CART_HIDDEN',
    ADD_ITEM_TO_CART:'ADD_ITEM_TO_CART',
    REMOVE_CART_ITEM:'REMOVE_CART_ITEM',
    DECREASE_CART_ITEM:'DECREASE_CART_ITEM',
    INCREASE_CART_ITEM:'INCREASE_CART_ITEM'
}

export default CartActionTypes;